version: '3'

services:
  php72:
    image: iordachej/php:7.2-fpm-alpine3.7-sf4
    volumes:
      - "./php-fpm/php-fpm.conf:/usr/local/etc/php-fpm.conf"
      - "./php-fpm/php.ini:/usr/local/etc/php/php.ini"
      - "./php-fpm/html:/var/www/html:rw"
      - "..:/usr/share/nginx:rw"
    environment:
      APP_ENV: prod
      APP_RUN_MODE: prod
#root   /usr/share/nginx/public_html

  nginx113:
    image: iordachej/ngnix:1.13-alpine
    ports:
      - 8888:80
    volumes:
      - "..:/usr/share/nginx:rw"
      - "./ngnix/nginx.conf:/etc/nginx/nginx.conf:rw"
      - "./ngnix/default.conf:/etc/nginx/conf.d/default.conf:rw"
    depends_on:
      - php72

